### ISSUE TITLE
owl2

### ISSUE THREAD

**Issue by itaybardan** [lunisolar/LNKD.tech-Editor#24]
Hey guys ;)
Can you add auto-complete support for owl2 syntax?
right now the plugin does not recognize it at all.
Thanks! @lunisolar

**Comment by lunisolar** [comment]
The plugin's auto-complete does not support any specific syntax/vocabulary/ontology. 
It takes all the TTL files available in the project and auto-completes from that (but **filtered by prefix/namespace declarations**). 

It also comes with 10-15 most common graphs like SKOS, FOAF, OWL2 as a form of "global graphs". All build-in and configured custom global graphs are just added to the project and auto-complete will use them too (filtered with prefix declrarations). 

That filtering by prefix declarations - It is measure of being "intelligent". The more files you would have in the project the longer would be (and resource extensive) the list of completion options (it also should work with empty or very short user entry). 
It threats prefix declarations like imports (not technically correct, but still necessary to be scalable)

1. If you have prefixes declared, 
2. check if OWL2 graph is actually selected as "global graph": Files/Settings/Other Settings/LNKD.tech Editor/Global Graphs. 

If that does not work then we have a bug - then i would gladly know more about specifics of your project.  
The auto completion also supports completing IRIs but (filtering by prefix declarations also applies)
