### ISSUE TITLE
Bug when enabling this plugin

### ISSUE THREAD

**Issue by claudiu-cristea** [lunisolar/LNKD.tech-Editor#25]
This plugin is the source of the bug described in https://intellij-support.jetbrains.com/hc/en-us/requests/3476081 and https://twitter.com/claudiu_cristea/status/1424662103286243330 (check the whole thread).

When I disable the plugin, the error is gone. Re-enabling it and I can see the error again.

**Comment by lunisolar** [comment]
Thanks for the report.
To be honest, I got it sometimes when the "Structure" tool is open in 2021.2.x.  But I have not connected it to my plugin. 
I will check it out in next few days.

**Comment by lunisolar** [comment]
It seems that somehow this plugin affects the "Structure" tool to work different way. It is kind of dynamic - it looks like "Structure" is stealing the focus, but it does not always interfere with user input. 
The weird thing is that when most of the plugin features are disabled (including support for "Structure") the issue still exists. 
Need more time to investigate this.

**Comment by lunisolar** [comment]
I've manage to fix a bug (aforementioned "Structure" tool issue) - not sure that this is "the" bug originally reported. There is however huge change. Rolling the release now, new build should be visible in JetBrains repository in middle of the week.
