### ISSUE TITLE
Plugin is not indexing some resources

### ISSUE THREAD

**Issue by Antoniossss** [lunisolar/LNKD.tech-Editor#29]
When I define a new resource like eg
```

@prefix wec:                  <http://someurl#> .
wec:globalTargetGraphProperty
   a sh:PropertyShape; 
   some other triples
.

```

for whatever resons plugin says ```Unresolved reference "http://someurl#globalTargetGraphProperty"```. Sometimes it works correctly and even allows me to navigate between ttl files by ctrl clicking resources, but frankly not always. 

Are there any requiremets for resources to be indexed properly across ttls files ? Do I have to somehow add ttl file to triplestore??

Updating from 0.11.2 to 011.5 did might have helped, but it could be just intellj restart as well. I will monitor the issue.

**Comment by lunisolar** [comment]
Sorry for overdue response.

I expect that this is caching issue. First implementation reference resolution in plugin did not used indexing at all, as it was not yet implemented. 

- does the reference existed before the resource was created? 
- does writing the same reference again after good 1 min after resource is created still does not resolve?
- does completion offer the new reference at those times?

I will try to reproduce this, but just not yet, as I'm too deeply into the Shacl validations for the 12.x version. 

**Are there any requirements for resources to be indexed properly across ttls files ?**

Indexing - Not really, any TTL file should be included automatically. There are however caveats. 

- It happens on IntelliJ request - that means some delay could be present - usually 1-5 sec + time the file is parsed (100ms - 9s depending on size of file, and CPU).  
- This plugin parses whole files for the purpose of indexing. The reason being that it is actual triple-store being use in the background (Jena). It is Jena actually doing parsing for the indexing - with the exception described bellow. 
- When there are syntax errors: 
-- Plugin uses its own parser used in IntelliJ editor. However this is slower - even if file is actually open and already "parsed". Parsing for editor is a lot heavier than stream parsing that RIOT is doing in Jena. But it allows to skip sections with errors and continue with rest of resources. 

In IntelliJ based IDEs you should be actually be able to force re-indexing. This includes restart - so for diagnostic purposes it will just rested everything.

**Comment by lunisolar** [comment]
After some investigation I now see that the same happens for SHACL inspection that I'm working on - and it is a blocker for both of them. I'm building solution now. 

To provide background: 
Inspections are triggered before file is indexed. It is drawback of aiming with the index to be in triple-store instead of usual IntelliJ way. 

I see two potential ways: 

- either I will find the IntelliJ way of doing it - kind of already did investigation that there is probably no way :(
- build more dynamic indexing (hybrid dataset - to include changed, but not yet saved changes)

**Comment by lunisolar** [comment]
Pending release: https://github.com/lunisolar/LNKD.tech-Editor/issues/30
