### ISSUE TITLE
Support new Alignment style for predicates

### ISSUE THREAD

**Issue by NicoMakowe** [lunisolar/LNKD.tech-Editor#42]
As a developer I'd like to have the possibility to format Turtles with a consistent indentation of 4 spaces.

The current formatter supports two Alignments for Predicates:

1. No new line after subject and vertical alignment of following predicates

```
ex:Alice a ex:Person ;
         ex:knows ex:Bob ;
         ex:likes ex:Claire .

ex:Bob a ex:Person ;
       ex:likes ex:Alice ;
       ex:knows ex:Claire .
```
2. New line after subject and no vertical indentation
```
ex:Alice 
a ex:Person ;
ex:knows ex:Bob ;
ex:likes ex:Claire .
```
Many developers don't like the first alignment style because the predicate lists won't be aligned with other predicate lists. The second one is also not perfect because one could easily confuse subjects, predicates and objects.

I would like to have an alignment method where the predicates in a new line have always the indentation that the user selected (e.g., 4 spaces)
```
ex:Alice a ex:Person ;
    ex:knows ex:Bob ;
    ex:likes ex:Claire .
```
This feature could also be expanded with object lists. Every object should then have a indentation of 8 spaces.

**Comment by jak-ub** [comment]
I think that same indent for all predicates is good idea. And I actually prefer this option. Including the objects. 
For the moment I need to fight with #37, but I will get back to this ticket.

**Comment by jak-ub** [comment]
- Option for Indentation of verbs was already there. 
- Now, I've added option "Always align verbs". To control if all verbs will align with the first one that is kept after the subject in the same line. 

TODO: 
- Continuation indent for objects was already there (it does not apply always). But also discovered one case where it did not apply correctly (when "each object in separate line" was selected together with two variants of object wrapping). 
- Seems like option "Wrap objects"=="Always wrap" does nothing (behaves just like "Do not wrap")

**Comment by jak-ub** [comment]
Pending release.
