### ISSUE TITLE
no way to dismiss issues reading SHACL shapes

### ISSUE THREAD

**Issue by osi** [lunisolar/LNKD.tech-Editor#55]
![image](https://github.com/lunisolar/LNKD.tech-Editor/assets/19927/6f9125e9-53a9-4b49-989b-73e3ca61648c)

when there is an issue reading SHACL shapes, the banner will appear multiple times with no way to dismiss it.

closing the tab and re-opening it makes them go away.

**Comment by jak-ub** [comment]
After some investigation, Ii seems to be a regression in the IntelliJ Platform itself: https://youtrack.jetbrains.com/issue/IJPL-995/Adding-a-ProblemDescriptor-to-a-file-for-its-entire-text-range-now-results-in-multiple-file-level-banners-being-added

JetBrains fixed it for upcoming IDE versions. But from what I checked on IntelliJ 2024.2 EAP, the fix itself is almost of the same level of annoyance (popup switches on and off, shifting the whole file text up and down every half second). 

I will keep observing what are they doing in that respect. If they will not fix it properly. I could always report the issue for the first line - although it would be less visible.

**Comment by osi** [comment]
thanks for digging! i hadn’t noticed this problem elsewhere and this hadn’t realized it was with intellij ***@***.*** - http://fotap.org/~osiOn May 19, 2024, at 9:05 AM, Jakub Wach ***@***.***> wrote:﻿
After some investigation, Ii seems to be a regression in the IntelliJ Platform itself: https://youtrack.jetbrains.com/issue/IJPL-995/Adding-a-ProblemDescriptor-to-a-file-for-its-entire-text-range-now-results-in-multiple-file-level-banners-being-added
JetBrains fixed it for upcoming IDE versions. But from what I checked on IntelliJ 2024.2 EAP, the fix itself is almost of the same level of annoyance (popup switches on and off, shifting the whole file text up and down every half second).
I will keep observing what are they doing in that respect. If they will not fix it properly. I could always report the issue for the first line - although it would be less visible.
